src/components/components.css, src/components/forms/form.css, src/pages/Home.js, src/pages/pages.css
Resolved the Topbar issue and also changed the styling of the texts in the home page
=> Resolved the topbar issue

src/components/forms/RegisterForm.js, src/pages/specific/UpdateProfile.js
Added advanced input validation and type checking.
=> Register form updates

package-lock.json, package.json, src/pages/admin/ModalGalleryManager.js, src/pages/admin/PhotoUpload.js
Front-end code to deleting photos from gallery
=> Gallery photo delete frontend

src/pages/admin/AdminLayout.js, src/pages/admin/admin.css
Changed Anchor tags to NavLink for active link
Added scrollbar in the sidebar
Added styling for active link
=> Admin Navigation Enhancements

src/components/components.css, src/pages/pages.css
Added background colour #f5f6fa, in pages.css and components.css and added media breakpoints for 640px,1024px,768px.
=> Added Background colour and media to fit tablet

src/components/common/PostCard.js, src/components/feed/FeedHome.js
…requests of api calls on every like
=> likes now update dynamically instead of refreshing the page to avoid multiple api calls

src/pages/detail/SingleEvent.js, src/pages/detail/SingleNews.js, src/pages/pages.css
Redesigned SingleEvent and SingleNews components while making both share the similar styling
=> Shared styles event news

src/components/common/PostCard.js, src/components/components.css, src/components/feed/feed.css
changed feed layout and made it responsive to view it better in tablets
=> Feed responsive layout changes

src/components/common/PostCard.js, src/components/common/PostList.js, src/components/components.css, src/components/feed/FeedHome.js
clicking on the comment button opens up a modal where users can reply Needs fixing though:
1. username is not being populated initially when the modal is opened
2. delete button disappears after a reply is deleted Someone please look into it, thanks
=> [NEEDS FIXING!] Comment section added which opens in modal

src/components/common/PostCard.js, src/components/components.css
fixed overflow of text in the postcard
fixed responsiveness
=> Feed Responsiveness And Overflow from PostCard Fix

src/components/common/CommentModal.js, src/components/components.css
Fixed some issues and added some functionalities-
1. Added pagination with 5 comments in a page
2. Preserved content formatting
3. Added word limit of 150 characters
Fixed-
1. Author id is now populated initially
Fixes required: Styling updates for alignment and responsive styling
=> Updated the comment modal section [see description]

src/pages/admin/ActionMenu.js, src/pages/admin/AdminEventsForm.js, src/pages/admin/AdminNewsForm.js, src/pages/admin/SharedImagesAddModal.js, src/pages/admin/SharedImagesDeleteModal.js, src/pages/admin/admin.css
- Added two new modal views for accomplishing this task.
- Under Action table heading, there was clutter with the 4 buttons(two previous and two new for deleting and images).
- To remove the clutter added a dropdown (3 vertical dots) action menu, which shows all the required actions.
=> Events and News Image Management

src/components/components.css, src/pages/specific/Profile.js
Clicking on a 'Recent Post' in profile page now no longer navigates a user to the feed. Instead, the corresponding post is now rendered in a modal.
=> Updated onClick function of recent posts

src/App.js, src/components/common/CommentModal.js, src/components/common/PostCard.js, src/components/common/ProfilePhotoComponent.js, src/components/components.css, src/components/feed/FeedHome.js, src/components/feed/FeedPostView.js, src/components/feed/feed.css, src/pages/specific/Profile.js
=> Single post component

src/App.js, src/components/ProtectedRoute.js, src/pages/detail/ErrorPage.js, src/pages/detail/SingleAlbum.js, src/pages/detail/SingleEvent.js, src/pages/detail/SingleNews.js, src/pages/pages.css
- added a new component ErrorPage for different errors
- added new routes in App.js for the errors
- changed the error handling in SingleAlbum, SingleEvent and SingleNews to navigate to different error pages for appropriate errors
- changed the navigation route in ProtectedRoute for the 403 forbidden
=> feat: new error page - 403, 404 and 500

src/pages/Home.js, src/pages/pages.css
Added the college photo in the hero section for the mobile view as well behind the text
=> Added the college photo in the hero section for the mobile view

src/pages/detail/SingleEvent.js, src/pages/detail/SingleNews.js, src/pages/pages.css
- added checks in SingleEvent and SingleNews to check if images are uploaded
- added css to make content take full width if no images are uploaded
- also increased font size of the content
=> style: if no images are uploaded, content takes full width

src/App.js, src/components/common/PostCard.js, src/pages/admin/AdminLayout.js, src/pages/admin/FlaggedPosts.js
posts can now be reported to admins and are displayed as a list in admin dashboard
=> added report functionality for posts

src/components/common/Pagination.js, src/pages/pages.css, src/pages/specific/Profile.js
-Fixed horizontal overflow of long text sentences in recent post sections for certain display resolutions 
-Updated the pagination component (displays 5 pages at a time and also added arrow keys for navigation)
=> Fixed some issues of  user profile page

src/pages/detail/SingleEvent.js, src/pages/detail/SingleNews.js, src/pages/pages.css
- used yet-another-react-lighbox to display images in a lightbox
- changes made to pages.css for the same and sticky of images
=> feat: added lightbox to news and events single page

src/components/common/Topbar.js, src/components/components.css, src/components/forms/form.css, src/pages/pages.css
- added active state to Topbar components
- used active state styling and made it responsive
- fixed the .main margin for below 680px
=> style: added active state style and other style fixes

src/App.js, src/components/common/Topbar.js, src/pages/admin/AdminLayout.js
- in App.js added new route for superuser and updated the existing routes to include the superuser
- in Topbar.js updated the conditional rendering of the admin dashboard to include the superuser
- in AdminLayout.js conditionally rendered the create admin for superuser
=> feat: superuser

src/components/common/ScrollToTop.js, src/components/feed/FeedPostView.js, src/index.js
- used ScrollToTop component to scroll to top on route change
- added ScrollToTop component to index.js and wrapped App component
- removed ScrollToTop useffect used explicitly in FeedPostView.js
=> fix: scroll to top on route change

src/components/common/Pagination.js, src/pages/detail/Events.js, src/pages/detail/NewsArchive.js, src/pages/pages.css, src/pages/specific/Profile.js
Pagination component:
-Updated the pagination styling, added first and last navigation buttons for better UI experience -Reused pagination component in news and events page
Profile page:
-Added a role badge for admins and superuser
=> Pagination and user profile updates

src/App.js, src/pages/articles/Gallery.js
- updated the route for singlealbum page in App.js and Gallery.js to highlight the gallery active tab in navbar when in singlealbum page
=> fix: gallery active tab in navbar was not highlighted when in single album page

src/components/common/EditEventModal.js, src/components/common/NewsEditModal.js
- weren't handling images in edit so no need for FormData. used JSON instead
- in EditEventModal, the put request wasn't being sent by api service so used that
- removed unnecessary image jsx in NewsEditModal
=> update FormData to JSON in both EditEventModal and NewsEditModal

src/components/common/RecommendedUsersList.js, src/components/feed/FeedHome.js
- Replace Link component with button in RecommendedUsersList
- Add onSwitchToFriends prop to handle tab switching
- Update Welcome component to pass tab switching handler
=> refactor(users): update 'Find Other Mates' button

src/components/forms/RegisterForm.js, src/components/forms/form.css
- Add stricter name validation (letters only)
- Removed duplicate email errors
- Improve password field UX with toggle
- Add proper ARIA labels
- Enhance error handling
- Changed phone number input type from text to tel for better mobile input
=> refactor(auth): enhance registration form validation and UX

src/components/common/EditEventModal.js, src/pages/pages.css
-also changed the font size of news and event articles to 1 rem
=> Fix content preservation in event edit modal
